services:
  client:
    image: node:17.5.0-alpine3.15
    container_name: proj_dev_client
    ports: 80:8080
    volumes:
      - type: bind
        source: ./client/
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run start"
  api:
    container_name: proj_dev_api
    ports: 3000:3000
    command: bash -c "npm install && npm run seedDev && npm run dev"
    restart: always
  db:
    container_name: proj_dev_db
    volumes:
      - dbdata:/var/lib/mongodb/data
    restart: always
volumes:
  dbdata:
networks:
  default:
    name: example_app_dev
