version: '3'
services:
  api:
    image: node:latest
    working_dir: /code
    restart: always
    ports:
      - 3000:3000
    environment:
      - DB_NAME=habit
      - DB_CONNECTION=mongodb://tracker:habits@db:27017
    volumes:
      - type: bind
        source: ./api
        target: /code
    command: bash -c "npm install && npm start"
    depends_on: 
      - db
      
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tracker
      - MONGO_INITDB_ROOT_PASSWORD=habits
      - MONGO_INITDB_DATABASE=habit
    volumes: 
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
      - "dbdata:/var/lib/mongodb/data"
volumes:
  dbdata:


