version: "3"
services:
  api:
    container_name: demo_test_api
    tty: true
  db:
    container_name: demo_test_db
    volumes: test_db:/var/lib/mongodb/data
volumes:
  test_db:
networks:
  default:
