version: "3"
services:
  api:
    container_name: proj_dev_api
    command: sh -c "npm install && npm run dev"
  db:
    container_name: proj_dev_db
    volumes:
      - dbdata:/var/lib/mongodb/data
volumes:
  dbdata:
networks:
  default:
